
services:
  app:
    build: .
    ports:
      - '3300:3300'
    depends_on:
      - mongo-db
    environment:
      - MONGO_URL=${MONGO_URL}
  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
